/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pertanyaan;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author SONY
 */
public class Question extends javax.swing.JFrame {

    public static void update(String text) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    int angka=1;
    int Angka=0;
    String jawaban="";
    String Betul ="";
    int Benar=0;
    int Salah=0;
    int Skor=0;
    String soal1[]={"Soal Verbal Antonim : Canggih","A. Sederhana","B. Kuno","C. Biasa","D. Modern"};
    String soal2[]={"Isilah angka berikutnya : 3, 6, 9, 12, 15","A. 16","B. 18","C. 17","D. 20"};
    String soal3[]={"Soal Verbal Analogi : Duren = Buah","A. Buku = Kertas","B. Mangkok = Sendok","C. Kangkung = Sayur","D. Belimbing = Manis"};
    String soal4[]={"Budi mempunyai adik bernama Susi, sedangkan Cahyo kakaknya Susi dan lebih muda daripada Budi. Siapakah diantara mereka yang paling muda?","A. Cahyo","B. Budi","C. Santo","D. Susi"};
    String soal5[]={"Carilah kosa kata yang tidak termasuk dalam kosakata dibawah ini!","A. Coklat","B. Susu","C. Gula","D. Minuman Instan"};
    String soal6[]={"Apa nama perusahaan teknologi terbesar di Korea Selatan ?","A. Apple","B. Microsoft","C. Samsung","D. Google"};
    String soal7[]={"Berapa banyak hati yang dimiliki oleh Gurita ?","A. 2","B. 4","C. 1","D. 3"};
    String soal8[]={"Colosseum merupakan landmark dari negara ?","A. Italia","B. Mesir","C. India","D. Iran"};
    String soal9[]={"Akhir dari Perang Dunia Pertama adalah tahun ?","A. 1920","B. 1918","C. 1945","D. 1900"};
    String soal10[]={"Penyanyi manakah yang dikenal sebagai The King of Pop ?","A. Justin Bieber","B. Dua Lipa","C. Michael Jackson","D. Beach Boys"};
    
    public Question() {
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        initComponents();
        soal.setText(""+soal1[0]);
        A.setText(""+soal1[1]);
        B.setText(""+soal1[2]);
        C.setText(""+soal1[3]);
        D.setText(""+soal1[4]);
        txtAngka.setText(""+angka);
        
    }
    
    public void Clear(){
        gruppil.clearSelection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gruppil = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        soal = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        A = new javax.swing.JRadioButton();
        B = new javax.swing.JRadioButton();
        C = new javax.swing.JRadioButton();
        D = new javax.swing.JRadioButton();
        next = new javax.swing.JButton();
        prev = new javax.swing.JButton();
        txtAngka = new javax.swing.JLabel();
        hasil = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Pertanyaan No.");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(531, 128, -1, -1));

        soal.setEditable(false);
        soal.setColumns(20);
        soal.setRows(5);
        jScrollPane1.setViewportView(soal);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(443, 175, 486, 195));

        jPanel1.setBackground(new java.awt.Color(18, 13, 13));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1370, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, -1));

        jPanel2.setBackground(new java.awt.Color(18, 13, 13));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1370, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 656, 1370, -1));

        gruppil.add(A);
        A.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        A.setText("jRadioButton1");
        A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AActionPerformed(evt);
            }
        });
        getContentPane().add(A, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 408, -1, -1));

        gruppil.add(B);
        B.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        B.setText("jRadioButton2");
        B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BActionPerformed(evt);
            }
        });
        getContentPane().add(B, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 449, -1, -1));

        gruppil.add(C);
        C.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        C.setText("jRadioButton3");
        C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CActionPerformed(evt);
            }
        });
        getContentPane().add(C, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 490, -1, -1));

        gruppil.add(D);
        D.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        D.setText("jRadioButton4");
        D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DActionPerformed(evt);
            }
        });
        getContentPane().add(D, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 538, -1, -1));

        next.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        next.setText(">>>  ");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });
        getContentPane().add(next, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 396, 69, 46));

        prev.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        prev.setText("<<<");
        prev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prevActionPerformed(evt);
            }
        });
        getContentPane().add(prev, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 526, 69, 46));

        txtAngka.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtAngka.setText("N");
        getContentPane().add(txtAngka, new org.netbeans.lib.awtextra.AbsoluteConstraints(734, 128, -1, -1));

        hasil.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        hasil.setText("Hasil");
        hasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasilActionPerformed(evt);
            }
        });
        getContentPane().add(hasil, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 460, 69, 45));

        jPanel3.setBackground(new java.awt.Color(102, 153, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1370, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1370, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
try{
        Angka+=1;
        angka+=1;
        txtAngka.setText(""+angka);
        if(Angka==1){
            
            if(B.isSelected()){
                Benar+=1;
            }else{
                Salah+=1;
            }
            Clear();
        }if(angka==2){
            
            soal.setText(""+soal2[0]);
            A.setText(""+soal2[1]);
            B.setText(""+soal2[2]);
            C.setText(""+soal2[3]);
            D.setText(""+soal2[4]);
        }if(Angka==2){
            if(B.isSelected()){
                Benar+=1;
            }else{
                Salah+=1;
            }
            Clear();
        }
        
        if(angka==3){
            soal.setText(""+soal3[0]);
            A.setText(""+soal3[1]);
            B.setText(""+soal3[2]);
            C.setText(""+soal3[3]);
            D.setText(""+soal3[4]);
        }if(Angka==3){
            if(C.isSelected()){
                Benar+=1;
            }else{
                Salah+=1;
            }
            Clear();
        }
        
        if(angka==4){
            soal.setText(""+soal4[0]);
            A.setText(""+soal4[1]);
            B.setText(""+soal4[2]);
            C.setText(""+soal4[3]);
            D.setText(""+soal4[4]);
        }if(Angka==4){
            if(D.isSelected()){
                Benar+=1;
            }else{
                Salah+=1;
            }
            Clear();
        }
        
        if(angka==5){
            soal.setText(""+soal5[0]);
            A.setText(""+soal5[1]);
            B.setText(""+soal5[2]);
            C.setText(""+soal5[3]);
            D.setText(""+soal5[4]);
        }if(Angka==5){
            if(D.isSelected()){
                Benar+=1;
            }else{
                Salah+=1;
            }
            Clear();
        }
        
        if(angka==6){
            soal.setText(""+soal6[0]);
            A.setText(""+soal6[1]);
            B.setText(""+soal6[2]);
            C.setText(""+soal6[3]);
            D.setText(""+soal6[4]);
        }if(Angka==6){
            if(C.isSelected()){
                Benar+=1;
            }else{
                Salah+=1;
            }
            Clear();
        }
        
        if(angka==7){
            soal.setText(""+soal7[0]);
            A.setText(""+soal7[1]);
            B.setText(""+soal7[2]);
            C.setText(""+soal7[3]);
            D.setText(""+soal7[4]);
        }if(Angka==7){
            if(D.isSelected()){
                Benar+=1;
            }else{
                Salah+=1;
            }
            Clear();
        }
        
        if(angka==8){
            soal.setText(""+soal8[0]);
            A.setText(""+soal8[1]);
            B.setText(""+soal8[2]);
            C.setText(""+soal8[3]);
            D.setText(""+soal8[4]);
        }if(Angka==8){
            if(A.isSelected()){
                Benar+=1;
            }else{
                Salah+=1;
            }
            Clear();
        }
        
        if(angka==9){
            soal.setText(""+soal9[0]);
            A.setText(""+soal9[1]);
            B.setText(""+soal9[2]);
            C.setText(""+soal9[3]);
            D.setText(""+soal9[4]);
        }if(Angka==9){
            if(B.isSelected()){
                Benar+=1;
            }else{
                Salah+=1;
            }
            Clear();
        }
        
        if(angka==10){
            soal.setText(""+soal10[0]);
            A.setText(""+soal10[1]);
            B.setText(""+soal10[2]);
            C.setText(""+soal10[3]);
            D.setText(""+soal10[4]);
        }if(Angka==10){
            if(C.isSelected()){
                Benar+=1;
            }else{
                Salah+=1;
            }
            Clear();
        }
            
        }catch (Exception e){
            Logger.getLogger(Question.class.getName()).log(Level.SEVERE, null, e);
        }
        Skor = Benar*10;
    }//GEN-LAST:event_nextActionPerformed

    
    private void AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AActionPerformed
        jawaban ="A";
        // TODO add your handling code here:
    }//GEN-LAST:event_AActionPerformed

    private void BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BActionPerformed
        jawaban ="B";
        // TODO add your handling code here:
    }//GEN-LAST:event_BActionPerformed

    private void CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CActionPerformed
        jawaban ="C";
        // TODO add your handling code here:
    }//GEN-LAST:event_CActionPerformed

    private void DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DActionPerformed
        jawaban ="D";
        // TODO add your handling code here:
    }//GEN-LAST:event_DActionPerformed

    private void hasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasilActionPerformed
//        JOptionPane.showMessageDialog(null, "Nama : "+nama+"\n"+"Umur : "+umur+"\n"+"Jenis Kelamin : "+kelamin+"\n"+"Benar : "+Benar+"\n"+"Salah : "+Salah);
        JOptionPane.showMessageDialog(null,"Benar : "+Benar+"\n"+"Salah : "+Salah+"\n"+"Skor : "+Skor);
        // TODO add your handling code here:
    }//GEN-LAST:event_hasilActionPerformed

    private void prevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prevActionPerformed
        
        Angka-=1;
        angka-=1;
        txtAngka.setText(""+angka);
        
        if(angka==0){
            txtAngka.setText("");
        }else{
            txtAngka.setText(""+angka);
        }
        if(angka==1){
            soal.setText(""+soal1[0]);
            A.setText(""+soal1[1]);
            B.setText(""+soal1[2]);
            C.setText(""+soal1[3]);
            D.setText(""+soal1[4]);
            if(Benar>1){
                Benar-=1;
            }if(Benar<0){
                Benar=0;
            }if(Salah>1){
                Salah-=1;
            }if(Salah<0){
                Salah=0;
            }
            
            Salah-=1;
        }else if(angka==2){
            soal.setText(""+soal2[0]);
            A.setText(""+soal2[1]);
            B.setText(""+soal2[2]);
            C.setText(""+soal2[3]);
            D.setText(""+soal2[4]);
        }else if(angka==3){
            soal.setText(""+soal3[0]);
            A.setText(""+soal3[1]);
            B.setText(""+soal3[2]);
            C.setText(""+soal3[3]);
            D.setText(""+soal3[4]);
        }else if(angka==4){
            soal.setText(""+soal4[0]);
            A.setText(""+soal4[1]);
            B.setText(""+soal4[2]);
            C.setText(""+soal4[3]);
            D.setText(""+soal4[4]);
        }else if(angka==5){
            soal.setText(""+soal5[0]);
            A.setText(""+soal5[1]);
            B.setText(""+soal5[2]);
            C.setText(""+soal5[3]);
            D.setText(""+soal5[4]);
        }else if(angka==6){
            soal.setText(""+soal6[0]);
            A.setText(""+soal6[1]);
            B.setText(""+soal6[2]);
            C.setText(""+soal6[3]);
            D.setText(""+soal6[4]);
        }else if(angka==7){
            soal.setText(""+soal7[0]);
            A.setText(""+soal7[1]);
            B.setText(""+soal7[2]);
            C.setText(""+soal7[3]);
            D.setText(""+soal7[4]);
        }else if(angka==8){
            soal.setText(""+soal8[0]);
            A.setText(""+soal8[1]);
            B.setText(""+soal8[2]);
            C.setText(""+soal8[3]);
            D.setText(""+soal8[4]);
        }else if(angka==9){
            soal.setText(""+soal9[0]);
            A.setText(""+soal9[1]);
            B.setText(""+soal9[2]);
            C.setText(""+soal9[3]);
            D.setText(""+soal9[4]);
        }else if(angka==10){
            soal.setText(""+soal10[0]);
            A.setText(""+soal10[1]);
            B.setText(""+soal10[2]);
            C.setText(""+soal10[3]);
            D.setText(""+soal10[4]);
        }
        Clear();
        
    }//GEN-LAST:event_prevActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Question.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Question.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Question.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Question.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Question().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton A;
    private javax.swing.JRadioButton B;
    private javax.swing.JRadioButton C;
    private javax.swing.JRadioButton D;
    private javax.swing.ButtonGroup gruppil;
    private javax.swing.JButton hasil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton next;
    private javax.swing.JButton prev;
    private javax.swing.JTextArea soal;
    private javax.swing.JLabel txtAngka;
    // End of variables declaration//GEN-END:variables
}
